import type { Resource } from "i18next";

const es = {
  common: { email: "Correo electrónico", password: "Contraseña", name: "Nombre", login: "Iniciar sesión", forgotPassword: "Recuperar contraseña", sending: "Enviando…", retry: "Inténtalo de nuevo.", loading: "Cargando {{caption}}…", noResults: "Sin resultados." },
  auth: {
    createAccount: "Crear cuenta", createCompany: "Crear empresa", companyTitle: "Crea tu empresa",
    companyDescription: "Tu correo está verificado. Completa tu espacio de trabajo.", registerDescription: "Te enviaremos un enlace para verificar tu correo.", loginDescription: "Accede a tu espacio de trabajo.",
    companyName: "Nombre de empresa", country: "País", selectCountry: "Selecciona un país", wait: "Espera…", enter: "Entrar", register: "Regístrate", hasAccount: "¿Ya tienes cuenta? ", noAccount: "¿Aún no tienes cuenta? ", forgotLink: "¿Olvidaste tu contraseña?",
    invalidCompany: "Revisa el nombre y el país de la empresa.", createCompanyError: "No se pudo crear la empresa. Inténtalo de nuevo.", invalidAccount: "Revisa los datos de la cuenta.", registerError: "No se pudo enviar la solicitud. Inténtalo de nuevo.", invalidCredentials: "Revisa el correo y la contraseña.", invalidResponse: "Respuesta de autenticación inválida.", loginError: "No se pudo iniciar sesión.", connectionError: "No se pudo conectar. Inténtalo de nuevo.", requestError: "No se pudo procesar la solicitud. Inténtalo de nuevo.",
    emailSent: "Si existe una cuenta con ese correo, recibirás un enlace.", forgotTitle: "Recuperar contraseña", sendLink: "Enviar enlace", backToLogin: "Volver a iniciar sesión",
    resetTitle: "Restablecer contraseña", invalidPassword: "La contraseña debe tener entre 8 y 128 caracteres.", invalidResetLink: "El enlace no es válido o ya venció.", invalidResetRequest: "El enlace no es válido o ya venció. Solicita otro.", requestAnotherLink: "Solicitar otro enlace", passwordChanged: "La contraseña se cambió. Inicia sesión para continuar.", newPassword: "Nueva contraseña", saving: "Guardando…", changePassword: "Cambiar contraseña",
    checkEmailTitle: "Revisa tu correo", checkEmailDescription: "Revisa tu correo si tienes una verificación pendiente. Si ya tienes cuenta, inicia sesión o recupera tu contraseña.", verificationSent: "Si tienes una verificación pendiente, recibirás un enlace.", resendVerification: "Reenviar verificación",
    verifiedTitle: "Verificación completada", verificationFailedTitle: "No se pudo verificar el correo", verifiedDescription: "Inicia sesión para continuar. La verificación no inicia una sesión automáticamente.", verificationFailedDescription: "El enlace puede haber vencido o ya no ser válido. Solicita otro desde la página de revisión del correo.", backToCheckEmail: "Volver a revisar el correo",
  },
  nav: {
    workspace: "Espacio de trabajo", main: "Navegación principal", home: "Inicio", products: "Productos", orders: "Ventas", newProduct: "Nuevo producto", product: "Producto",
    toggleTheme: "Alternar tema", lightMode: "Modo claro", darkMode: "Modo oscuro", signingOut: "Cerrando sesión…", signOut: "Cerrar sesión", signOutError: "No se pudo cerrar la sesión. Inténtalo de nuevo.",
    skipContent: "Saltar al contenido", mainMenu: "Menú principal", closeMenu: "Cerrar menú", openMenu: "Abrir menú", breadcrumb: "Ruta de navegación",
    greeting: "Hola, {{name}}", ready: "Tu espacio de trabajo está listo.",
  },
  products: {
    title: "Productos", new: "Nuevo producto", newDescription: "Completa los datos para agregarlo a tu empresa.", name: "Nombre", multipleVariants: "Varias variantes", noSku: "Sin SKU", salePrice: "Precio de venta", purchasePrice: "Precio de compra", from: "Desde ", stock: "Stock", searchLabel: "Buscar por nombre o SKU", search: "Buscar", caption: "Productos del catálogo", emptySearch: "No se encontraron productos para esta búsqueda.", empty: "Aún no hay productos en el catálogo. ", createFirst: "Crea el primero", pages: "Páginas de productos", page: "Página {{page}}", invalidSearch: "Búsqueda no válida", loadError: "No se pudo cargar el catálogo", invalidSearchDescription: "Revisa los criterios e inténtalo de nuevo.", retry: "Reintentar", backCatalog: "Volver al catálogo", backProducts: "Volver a productos", saved: "Producto guardado correctamente.", saveChanges: "Guardar cambios", variants: "Variantes", variant: "Variante {{number}}", noPrice: "Sin precio", missing: "Producto no encontrado", loadProductError: "No se pudo cargar el producto", missingDescription: "No hay un producto disponible en esta dirección.", backHome: "Volver al inicio",
    readonlyVariants: "Puedes editar los datos generales y la foto. Las variantes son de solo lectura.", data: "Datos del producto", description: "Descripción", priceVariant: "Precio y variante", initialStock: "Stock inicial", photo: "Foto", removePhoto: "Quitar foto", uploading: "Subiendo imagen…", preview: "Vista previa de la foto del producto", saving: "Guardando…", save: "Guardar producto", cancel: "Cancelar", imageTooLarge: "La imagen supera el tamaño máximo de 10 MB.", invalidImage: "El archivo debe ser una imagen JPG, PNG o WebP.", uploadError: "No se pudo subir la imagen. Inténtalo de nuevo.",
  },
  orders: {
    title: "Ventas", new: "Nueva venta", view: "Ver ventas", completed: "Venta completada", instant: "Cobro y entrega en el momento", addProducts: "Agrega productos", addDescription: "Busca un producto y añádelo a la venta.", searchProducts: "Buscar productos por nombre", productName: "Nombre del producto", search: "Buscar", uniqueVariant: "Variante única", stock: "Stock", add: "Agregar", addNamed: "Agregar {{name}}", noProduct: "No encontramos ese producto", noProducts: "Todavía no hay productos", tryAnother: "Prueba con otro nombre o crea el producto para venderlo.", createFirst: "Crea el primero para comenzar a vender.", missingCatalog: "¿No está en el catálogo? ", createOtherTab: "Crear producto en otra pestaña", current: "Venta actual", itemCount_one: "{{count}} producto", itemCount_other: "{{count}} productos", empty: "Tu venta está vacía", emptyHint: "Agrega productos para comenzar.", quantity: "Cantidad", remove: "Quitar", shownTotal: "Total mostrado", currencyMismatch: "Los productos deben tener la misma moneda.", customer: "Cliente", generalPublic: "Público general", close: "Cerrar", change: "Cambiar", searchCustomer: "Buscar cliente por nombre o teléfono", nameOrPhone: "Nombre o teléfono", select: "Seleccionar", finalPriceHint: "El precio final se calcula al completar la venta. Confirma que recibiste el total por billetera digital y entregaste los productos.", completing: "Completando…", complete: "Confirmar cobro y completar venta", review: "Revisar venta", pointOfSaleError: "No se pudo cargar el punto de venta",
    invalidOrder: "Revisa los datos de la venta.", insufficientStock: "No hay stock suficiente para uno de los productos.", alreadyExists: "Esta venta ya se registró. Revisa el historial antes de intentar otra.", contactMissing: "El cliente ya no está disponible.", variantMissing: "Uno de los productos ya no está disponible.", saveError: "No se pudo completar la venta. Inténtalo de nuevo.",
    dateTime: "Fecha y hora", total: "Total", completedSales: "Ventas completadas", emptyFiltered: "No hay ventas para estos filtros.", pages: "Páginas de ventas", page: "Página {{page}}", previous: "Anterior", next: "Siguiente", searchContactFilter: "Buscar contacto para filtrar", searchContact: "Buscar contacto", filters: "Filtros", activeFilter_one: "{{count}} filtro activo", activeFilter_other: "{{count}} filtros activos", filterTitle: "Filtros de ventas", filterDescription: "Refina las ventas por cliente y fecha.", allCustomers: "Todos los clientes", contact: "Contacto", selectContact: "Seleccionar contacto", contactHint: "Busca un contacto en la barra sobre las ventas para encontrarlo aquí.", saleDate: "Fecha de venta", from: "Desde", before: "Antes de", clear: "Limpiar", apply: "Aplicar filtros", invalidFilters: "Filtros no válidos", listError: "No se pudieron cargar las ventas", invalidFiltersHint: "Revisa los filtros e inténtalo de nuevo.", backSales: "Volver a ventas",
    payment: "Pago", paymentConfirmed: "Billetera digital, confirmado", phoneAtSale: "Teléfono al vender", seller: "Vendedor", missing: "Venta no encontrada", loadError: "No se pudo cargar la venta", missingHint: "La venta no está disponible en esta empresa.",
  },
  productErrors: {
    label: { id: "identificador", name: "nombre", description: "descripción", sku: "SKU", salePrice: "precio de venta", purchasePrice: "precio de compra", initialStock: "stock inicial", currency: "moneda", imageId: "imagen", variants: "variantes", attributes: "atributos" },
    subject: { id: "El identificador", name: "El nombre", description: "La descripción", sku: "El SKU", salePrice: "El precio de venta", purchasePrice: "El precio de compra", initialStock: "El stock inicial", currency: "La moneda", imageId: "La imagen", variants: "Las variantes", attributes: "Los atributos" },
    requiredVariant: "Se requiere al menos una variante.", requiredMasculine: "{{subject}} es obligatorio.", requiredFeminine: "{{subject}} es obligatoria.", tooLong: "{{subject}} debe tener como máximo {{maxLength}} caracteres.", invalidCurrency: "La moneda no es válida.", invalidPrice: "El {{label}} debe estar entre {{minimum}} y {{maximum}}.", invalidPrecision: "El {{label}} admite hasta {{maxDecimals}} decimales.", invalidStock: "El stock inicial debe ser un número entero no negativo.", invalidTotalStock: "El stock total no puede superar el máximo permitido.", duplicateSku: "El SKU está repetido.", duplicateAttributes: "Las variantes deben ser distintas.", duplicateVariant: "No se puede repetir una variante.", variantNotFound: "La variante no pertenece a este producto.", invalidAttributes: "Los atributos no son válidos.", invalidType: "El valor de {{label}} no es válido.", unknownField: "La solicitud contiene campos no permitidos.", invalidId: "El identificador no es válido.", invalidValue: "El valor no es válido.", productNotFound: "El producto ya no está disponible.", skuInUse: "Este SKU ya está en uso.", idConflict: "El identificador ya está en uso.", imageNotFound: "La imagen ya no está disponible.", persistenceUnavailable: "No se pudo verificar la imagen. Inténtalo de nuevo.", invalidStoredData: "No se pudo leer el producto. Inténtalo de nuevo.", malformedJson: "La solicitud no es válida. Inténtalo de nuevo.", saveError: "No se pudo guardar el producto. Inténtalo de nuevo.",
  },
} as const;

const pt = {
  common: { email: "E-mail", password: "Senha", name: "Nome", login: "Entrar", forgotPassword: "Recuperar senha", sending: "Enviando…", retry: "Tente novamente.", loading: "Carregando {{caption}}…", noResults: "Nenhum resultado." },
  auth: {
    createAccount: "Criar conta", createCompany: "Criar empresa", companyTitle: "Crie sua empresa",
    companyDescription: "Seu e-mail foi verificado. Configure seu espaço de trabalho.", registerDescription: "Enviaremos um link para verificar seu e-mail.", loginDescription: "Acesse seu espaço de trabalho.",
    companyName: "Nome da empresa", country: "País", selectCountry: "Selecione um país", wait: "Aguarde…", enter: "Entrar", register: "Cadastre-se", hasAccount: "Já tem uma conta? ", noAccount: "Ainda não tem uma conta? ", forgotLink: "Esqueceu sua senha?",
    invalidCompany: "Confira o nome e o país da empresa.", createCompanyError: "Não foi possível criar a empresa. Tente novamente.", invalidAccount: "Confira os dados da conta.", registerError: "Não foi possível enviar a solicitação. Tente novamente.", invalidCredentials: "Confira o e-mail e a senha.", invalidResponse: "Resposta de autenticação inválida.", loginError: "Não foi possível entrar.", connectionError: "Não foi possível conectar. Tente novamente.", requestError: "Não foi possível processar a solicitação. Tente novamente.",
    emailSent: "Se houver uma conta com esse e-mail, você receberá um link.", forgotTitle: "Recuperar senha", sendLink: "Enviar link", backToLogin: "Voltar para entrar",
    resetTitle: "Redefinir senha", invalidPassword: "A senha deve ter entre 8 e 128 caracteres.", invalidResetLink: "O link é inválido ou expirou.", invalidResetRequest: "O link é inválido ou expirou. Solicite outro.", requestAnotherLink: "Solicitar outro link", passwordChanged: "A senha foi alterada. Entre para continuar.", newPassword: "Nova senha", saving: "Salvando…", changePassword: "Alterar senha",
    checkEmailTitle: "Confira seu e-mail", checkEmailDescription: "Confira seu e-mail se houver uma verificação pendente. Se já tem uma conta, entre ou recupere sua senha.", verificationSent: "Se houver uma verificação pendente, você receberá um link.", resendVerification: "Reenviar verificação",
    verifiedTitle: "Verificação concluída", verificationFailedTitle: "Não foi possível verificar o e-mail", verifiedDescription: "Entre para continuar. A verificação não inicia uma sessão automaticamente.", verificationFailedDescription: "O link pode ter expirado ou deixado de ser válido. Solicite outro na página de verificação do e-mail.", backToCheckEmail: "Voltar para verificar o e-mail",
  },
  nav: {
    workspace: "Espaço de trabalho", main: "Navegação principal", home: "Início", products: "Produtos", orders: "Vendas", newProduct: "Novo produto", product: "Produto",
    toggleTheme: "Alternar tema", lightMode: "Modo claro", darkMode: "Modo escuro", signingOut: "Saindo…", signOut: "Sair", signOutError: "Não foi possível sair. Tente novamente.",
    skipContent: "Ir para o conteúdo", mainMenu: "Menu principal", closeMenu: "Fechar menu", openMenu: "Abrir menu", breadcrumb: "Caminho de navegação",
    greeting: "Olá, {{name}}", ready: "Seu espaço de trabalho está pronto.",
  },
  products: {
    title: "Produtos", new: "Novo produto", newDescription: "Preencha os dados para adicioná-lo à sua empresa.", name: "Nome", multipleVariants: "Várias variantes", noSku: "Sem SKU", salePrice: "Preço de venda", purchasePrice: "Preço de compra", from: "A partir de ", stock: "Estoque", searchLabel: "Buscar por nome ou SKU", search: "Buscar", caption: "Produtos do catálogo", emptySearch: "Nenhum produto encontrado para esta busca.", empty: "Ainda não há produtos no catálogo. ", createFirst: "Crie o primeiro", pages: "Páginas de produtos", page: "Página {{page}}", invalidSearch: "Busca inválida", loadError: "Não foi possível carregar o catálogo", invalidSearchDescription: "Confira os critérios e tente novamente.", retry: "Tentar novamente", backCatalog: "Voltar ao catálogo", backProducts: "Voltar aos produtos", saved: "Produto salvo com sucesso.", saveChanges: "Salvar alterações", variants: "Variantes", variant: "Variante {{number}}", noPrice: "Sem preço", missing: "Produto não encontrado", loadProductError: "Não foi possível carregar o produto", missingDescription: "Não há um produto disponível neste endereço.", backHome: "Voltar ao início",
    readonlyVariants: "Você pode editar os dados gerais e a foto. As variantes são somente leitura.", data: "Dados do produto", description: "Descrição", priceVariant: "Preço e variante", initialStock: "Estoque inicial", photo: "Foto", removePhoto: "Remover foto", uploading: "Enviando imagem…", preview: "Prévia da foto do produto", saving: "Salvando…", save: "Salvar produto", cancel: "Cancelar", imageTooLarge: "A imagem excede o tamanho máximo de 10 MB.", invalidImage: "O arquivo deve ser uma imagem JPG, PNG ou WebP.", uploadError: "Não foi possível enviar a imagem. Tente novamente.",
  },
  orders: {
    title: "Vendas", new: "Nova venda", view: "Ver vendas", completed: "Venda concluída", instant: "Pagamento e entrega na hora", addProducts: "Adicione produtos", addDescription: "Busque um produto e adicione-o à venda.", searchProducts: "Buscar produtos por nome", productName: "Nome do produto", search: "Buscar", uniqueVariant: "Variante única", stock: "Estoque", add: "Adicionar", addNamed: "Adicionar {{name}}", noProduct: "Não encontramos esse produto", noProducts: "Ainda não há produtos", tryAnother: "Tente outro nome ou crie o produto para vendê-lo.", createFirst: "Crie o primeiro para começar a vender.", missingCatalog: "Não está no catálogo? ", createOtherTab: "Criar produto em outra aba", current: "Venda atual", itemCount_one: "{{count}} produto", itemCount_other: "{{count}} produtos", empty: "Sua venda está vazia", emptyHint: "Adicione produtos para começar.", quantity: "Quantidade", remove: "Remover", shownTotal: "Total exibido", currencyMismatch: "Os produtos devem ter a mesma moeda.", customer: "Cliente", generalPublic: "Público geral", close: "Fechar", change: "Alterar", searchCustomer: "Buscar cliente por nome ou telefone", nameOrPhone: "Nome ou telefone", select: "Selecionar", finalPriceHint: "O preço final é calculado ao concluir a venda. Confirme que recebeu o total por carteira digital e entregou os produtos.", completing: "Concluindo…", complete: "Confirmar pagamento e concluir venda", review: "Revisar venda", pointOfSaleError: "Não foi possível carregar o ponto de venda",
    invalidOrder: "Confira os dados da venda.", insufficientStock: "Estoque insuficiente para um dos produtos.", alreadyExists: "Esta venda já foi registrada. Confira o histórico antes de tentar outra.", contactMissing: "O cliente não está mais disponível.", variantMissing: "Um dos produtos não está mais disponível.", saveError: "Não foi possível concluir a venda. Tente novamente.",
    dateTime: "Data e hora", total: "Total", completedSales: "Vendas concluídas", emptyFiltered: "Não há vendas para esses filtros.", pages: "Páginas de vendas", page: "Página {{page}}", previous: "Anterior", next: "Próxima", searchContactFilter: "Buscar contato para filtrar", searchContact: "Buscar contato", filters: "Filtros", activeFilter_one: "{{count}} filtro ativo", activeFilter_other: "{{count}} filtros ativos", filterTitle: "Filtros de vendas", filterDescription: "Refine as vendas por cliente e data.", allCustomers: "Todos os clientes", contact: "Contato", selectContact: "Selecionar contato", contactHint: "Busque um contato na barra acima das vendas para encontrá-lo aqui.", saleDate: "Data da venda", from: "Desde", before: "Antes de", clear: "Limpar", apply: "Aplicar filtros", invalidFilters: "Filtros inválidos", listError: "Não foi possível carregar as vendas", invalidFiltersHint: "Confira os filtros e tente novamente.", backSales: "Voltar às vendas",
    payment: "Pagamento", paymentConfirmed: "Carteira digital, confirmado", phoneAtSale: "Telefone no momento da venda", seller: "Vendedor", missing: "Venda não encontrada", loadError: "Não foi possível carregar a venda", missingHint: "A venda não está disponível nesta empresa.",
  },
  productErrors: {
    label: { id: "identificador", name: "nome", description: "descrição", sku: "SKU", salePrice: "preço de venda", purchasePrice: "preço de compra", initialStock: "estoque inicial", currency: "moeda", imageId: "imagem", variants: "variantes", attributes: "atributos" },
    subject: { id: "O identificador", name: "O nome", description: "A descrição", sku: "O SKU", salePrice: "O preço de venda", purchasePrice: "O preço de compra", initialStock: "O estoque inicial", currency: "A moeda", imageId: "A imagem", variants: "As variantes", attributes: "Os atributos" },
    requiredVariant: "É necessária pelo menos uma variante.", requiredMasculine: "{{subject}} é obrigatório.", requiredFeminine: "{{subject}} é obrigatória.", tooLong: "{{subject}} deve ter no máximo {{maxLength}} caracteres.", invalidCurrency: "A moeda não é válida.", invalidPrice: "O {{label}} deve estar entre {{minimum}} e {{maximum}}.", invalidPrecision: "O {{label}} aceita até {{maxDecimals}} casas decimais.", invalidStock: "O estoque inicial deve ser um número inteiro não negativo.", invalidTotalStock: "O estoque total não pode ultrapassar o máximo permitido.", duplicateSku: "O SKU está duplicado.", duplicateAttributes: "As variantes devem ser diferentes.", duplicateVariant: "Não é possível repetir uma variante.", variantNotFound: "A variante não pertence a este produto.", invalidAttributes: "Os atributos não são válidos.", invalidType: "O valor de {{label}} não é válido.", unknownField: "A solicitação contém campos não permitidos.", invalidId: "O identificador não é válido.", invalidValue: "O valor não é válido.", productNotFound: "O produto não está mais disponível.", skuInUse: "Este SKU já está em uso.", idConflict: "O identificador já está em uso.", imageNotFound: "A imagem não está mais disponível.", persistenceUnavailable: "Não foi possível verificar a imagem. Tente novamente.", invalidStoredData: "Não foi possível ler o produto. Tente novamente.", malformedJson: "A solicitação não é válida. Tente novamente.", saveError: "Não foi possível salvar o produto. Tente novamente.",
  },
};

const resources = { es: { translation: es }, pt: { translation: pt } } satisfies Resource;

export default resources;

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "translation";
    resources: typeof resources.es;
  }
}
