import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/legacy-redirect.ts", { id: "legacy-home" }),
  route("login", "routes/login.tsx", { id: "public-login" }),
  route("register", "routes/register.tsx", { id: "public-register" }),
  route("check-email", "routes/check-email.tsx"),
  route("account-verified", "routes/account-verified.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  layout("routes/private-layout.tsx", { id: "public-private-layout" }, [
    route("dashboard", "routes/dashboard.tsx", { id: "public-dashboard" }),
    route("products", "routes/product-list.tsx", { id: "public-product-list" }),
    route("products/new", "routes/product-new.tsx", { id: "public-product-new" }),
    route("products/:productId/edit", "routes/product-edit.tsx", { id: "public-product-edit" }),
    route("products/:productId", "routes/product-detail.tsx", { id: "public-product-detail" }),
    route("settings/delivery", "routes/delivery-settings.tsx", { id: "public-delivery-settings" }),
    route("orders/new", "routes/order-new.tsx", { id: "public-order-new" }),
    route("orders", "routes/order-list.tsx", { id: "public-order-list" }),
    route("orders/:orderId", "routes/order-detail.tsx", { id: "public-order-detail" }),
  ]),
  route(":locale", "routes/locale-layout.tsx", [
    index("routes/home.tsx"),
    route("login", "routes/login.tsx", { id: "localized-login" }),
    route("register", "routes/register.tsx", { id: "localized-register" }),
    route("check-email", "routes/check-email.tsx", { id: "localized-check-email" }),
    route("account-verified", "routes/account-verified.tsx", { id: "localized-account-verified" }),
    route("forgot-password", "routes/forgot-password.tsx", { id: "localized-forgot-password" }),
    route("reset-password", "routes/reset-password.tsx", { id: "localized-reset-password" }),
    layout("routes/private-layout.tsx", { id: "localized-private-layout" }, [
      route("dashboard", "routes/dashboard.tsx", { id: "localized-dashboard" }),
      route("products", "routes/product-list.tsx", { id: "localized-product-list" }),
      route("products/new", "routes/product-new.tsx", { id: "localized-product-new" }),
      route("products/:productId/edit", "routes/product-edit.tsx", { id: "localized-product-edit" }),
      route("products/:productId", "routes/product-detail.tsx", { id: "localized-product-detail" }),
      route("settings/delivery", "routes/delivery-settings.tsx", { id: "localized-delivery-settings" }),
      route("orders/new", "routes/order-new.tsx", { id: "localized-order-new" }),
      route("orders", "routes/order-list.tsx", { id: "localized-order-list" }),
      route("orders/:orderId", "routes/order-detail.tsx", { id: "localized-order-detail" }),
    ]),
  ]),
] satisfies RouteConfig;
