export type TransportError = Readonly<{
  code:
    | "UNAUTHENTICATED"
    | "COMPANY_REQUIRED"
    | "INVALID_COMPANY"
    | "INVALID_IMAGE"
    | "IMAGE_TOO_LARGE"
    | "UNSUPPORTED_MEDIA_TYPE"
    | "IMAGE_STORAGE_UNAVAILABLE"
    | "NOT_FOUND"
    | "SERVICE_UNAVAILABLE"
    | "NETWORK_ERROR"
    | "RATE_LIMITED"
    | "SERVER_ERROR"
    | "INVALID_RESPONSE"
    | "OPERATION_CANCELLED"
    | "SECURE_STORAGE_ERROR";
  message: string;
}>;
